import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=new URL('../assets/',import.meta.url);
const t=JSON.parse(await fs.readFile(new URL('tokens.json',root),'utf8'));
const css=[`/* Generated by scripts/build-tokens.mjs. Edit tokens.json. */`,':root{',
 `--page-width:${t.canvas.width}px;--page-height:${t.canvas.height}px;`,
 ...['paper','ink','muted','rule','surface'].map(k=>`--${k}:${t.canvas[k]};`),
 `--margin-x:${t.layout.marginX}px;--margin-top:${t.layout.marginTop}px;--footer-bottom:${t.layout.footerBottom}px;`,
 ...Object.entries(t.type).map(([k,v])=>`--${k}-size:${v.size}px;--${k}-leading:${v.lineHeight};`),
 `--pigment:${t.themes.zhusha.pigment};--accent-text:${t.themes.zhusha.text};--wash:${t.themes.zhusha.wash};`,'}',
 ...Object.entries(t.themes).map(([k,v])=>`[data-theme="${k}"]{--pigment:${v.pigment};--accent-text:${v.text};--wash:${v.wash}}`)
].join('\n');
await fs.writeFile(new URL('tokens.css',root),css+'\n');
console.log(fileURLToPath(new URL('tokens.css',root)));
